### PR TITLE
Add CoKleisli

### PR DESCRIPTION
**Pull request by paf31**
@garyb @joneshf Look ok?

### CODE REVIEW

**Comment by garyb** [comment]
:+1:

**Comment by ethul** [comment]
Sorry I am late on this, but I am wondering if there is a naming scheme for `Co*`? For instance we have:

`Comonad`

https://github.com/purescript/purescript-control/blob/master/src/Control/Comonad.purs#L5

Should we have `Cokleisli` or `CoKleisli`?

**Comment by paf31** [comment]
Good point. I basically just copied the Haskell naming, but I didn't release this yet, so we can change it.

**Comment by paf31** [comment]
I guess I figured Kleisli is a [proper name](https://en.wikipedia.org/wiki/Heinrich_Kleisli) so it sort of seemed odd to remove the upper case :)

**Comment by ethul** [comment]
I could go either way.

I see in scalaz there was a commit to prefer `Cokleisli` over `CoKleisli`:
https://github.com/scalaz/scalaz/commit/10b656ad39c7b00e9418208e03ef2a09a9447c43

But in Haskell it looks like `CoKleisli` is used.

Maybe consistency would be best?

I am not really sure the best call for this.

**Comment by garyb** [comment]
Ah actually yeah, maybe we should go with the sentence case version, as we have that with `Comonad` and also things like `Semiring`.

**Comment by paf31** [comment]
If it weren't a name, I would definitely agree. As it is, I don't care enough to make a strong case either way :)

**Comment by paf31** [comment]
Done :+1:

**Comment by ethul** [comment]
Looks good, thanks for the rename!

**Pull request merged**
